# Generated by Django 6.0.6 on 2026-06-24 12:42

from django.db import migrations

def create_unique_brands(apps, schema_editor):
    ShoeModel = apps.get_model('main_app', 'Shoe')
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrand')

    # SELECT * FROM shoe;
    # shoes = ShoeModel.objects.all()
    # print({s.brand for s in shoes})

    # SELECT DISTINCT brand FROM shoe;
    unique_brands = ShoeModel.objects.values_list('brand', flat=True).distinct()

    # for b in unique_brands:
    #     brand = UniqueBrandsModel(brand=b)
    #     brand.save()  # INSERT ONLY ONE ROW;

    unique_brands_to_create = [UniqueBrandsModel(brand_name=b) for b in unique_brands]
    UniqueBrandsModel.objects.bulk_create(unique_brands_to_create)  # INSERT multiple records at once


def reverse_create_unique_brands(apps, schema_editor):
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrand')
    UniqueBrandsModel.objects.all().delete()  # DELETE FROM unique_brands;


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrand'),
    ]

    operations = [
        migrations.RunPython(
            code=create_unique_brands,
            reverse_code=reverse_create_unique_brands,
        )
    ]