# Generated by Django 6.0.6 on 2026-06-24 12:42

from django.db import migrations

def age_group_filler(apps, schema_editor):
    PersonModule = apps.get_model("main_app", "Person")

    for p in PersonModule.objects.all():
        if p.age < 13:
            p.age_group = "Child"
        elif p.age < 18:
            p.age_group = "Teen"
        else:
            p.age_group = "Adult"

        p.save()


def reverse_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')
    default_field = PersonModel._meta.get_field('age_group').default

    # research bulk_update
    for p in PersonModel.objects.all():
        p.age_group = default_field
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_course_eventregistration_item_movie_order_person_and_more'),
    ]

    operations = [
        migrations.RunPython( code= age_group_filler(),
                              reverse_code= reverse_age_group

        )
    ]