# Generated by Django 6.0.6 on 2026-06-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
