# Generated by Django 6.0.6 on 2026-06-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='difficulty',
            new_name='difficulty_level',
        ),
    ]
