# Generated by Django 6.0.7 on 2026-07-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='website_url',
            field=models.URLField(error_messages={'invalid': 'Enter a valid URL'}),
        ),
    ]
