# Generated by Django 6.0.7 on 2026-07-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_book_movie_music'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Model Music', 'verbose_name_plural': 'Models of type - Music'},
        ),
    ]
