# Generated by Django 6.0.6 on 2026-06-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='spices',
            new_name='species',
        ),
    ]
