# Generated by Django 6.0.6 on 2026-06-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_spices_pet_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('origin', models.CharField(max_length=70)),
                ('age', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('is_magical', models.BooleanField(default=False)),
            ],
        ),
    ]
